version: "3.5"
services:
  paper_prediction_localdb:
    image: postgres:15
    hostname: paper_prediction_localdb
    ports:
      - "6432:5432"
    shm_size: 4gb
    environment:
      POSTGRES_PORT: 6432
      POSTGRES_DB: paper_prediction
      POSTGRES_USER: team_14
      POSTGRES_PASSWORD: local_team14_password

networks:
  default:
     name: paper_prediction_localdb_network
